# SPDX-FileCopyrightText: 2017 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

# Default configuration for EventStream service
# This file contains all available configuration options with their default values
# 
# Configuration can be customized by:
# 1. Creating a custom YAML file and using the --config flag
# 2. Setting environment variables (see individual field comments for env var names)
# 3. Overriding specific sections in additional config files
#
# The service accepts both JSON and MessagePack formatted WRP messages at the /api/events endpoint
#
# Example usage:
#   ./eventstream --config /path/to/custom.yaml
#   ./eventstream --config default.yaml --config overrides.yaml
#
# For testing with curl:
#   curl -X POST -H "Content-Type: application/json" \
#        -u "eventstream:eventstream-password" \
#        -d '{"msg_type": 4, "source": "dns:test.example.com", "dest": "event:device-status/mac:112233445566/online"}' \
#        http://localhost:8080/api/events


# Filter manager configuration
filter_manager:
  delivery_retries: 3
  default_queue_size: 1000
  default_batch_size: 100
  default_max_workers: 1000
  
  # Filter configurations
  filters:
    - # Example: Device status events filter for Kinesis
      stream:
        stream_name: "comcast-cl.device-status.local"
        config:
          endpoint: "http://localhost:4567"       # Kinesis endpoint
          region: "local"                         # AWS region
          access_key: "myAccessKey"                  # AWS access key
          secret_key: "mySecretKey"                  # AWS secret key
          session_token: "mySessionToken"            # AWS session token (optional)
          version: "1.0"                          # Stream version
      
      # Alternative streams for failover (optional)
      alt_streams: []
      
      # Event patterns to match using regex
      events:
        - "device-status.*"                       # Matches device-status/online, device-status/offline, etc.
        # - "device-.*"                           # Would match any device events
        # - "boot-time"                           # Would match specific boot-time events
      
      # Metadata filtering configuration
      metadata:
        device_ids: []                             # Device ID patterns using regex (empty means all devices)
        # deviceIds:                              # Example device ID patterns:
        #   - "mac:.*"                            # Match all MAC addresses
        #   - "uuid:550e8400-.*"                  # Match specific UUID patterns
      
      # Destination type (kinesis, webhook, etc.)
      dest_type: "kinesis"
      
      # Stream version identifier
      stream_version: "1.0"
      
      # Performance tuning (optional - will use defaults if not specified)
      queue_size: 100     # Number of events to buffer before dropping (default: 1000)
      batch_size: 1       # Number of events to batch together (default: 100)
      max_workers: 100    # Maximum concurrent workers (default: 1000)

    # Additional filter example (commented out):
    # - stream:
    #     streamName: "comcast-cl.boot-events.prod"
    #     config:
    #       Endpoint: "https://kinesis.us-east-1.amazonaws.com"
    #       Region: "us-east-1"
    #       AccessKey: "${AWS_ACCESS_KEY}"        # Environment variable reference
    #       SecretKey: "${AWS_SECRET_KEY}"
    #       Version: "2.0"
    #   events:
    #     - "boot-time"
    #     - "firmware-update.*"
    #   metadata:
    #     deviceIds:
    #       - "mac:112233.*"                      # Only specific MAC prefix
    #   destType: "kinesis"
    #   streamVersion: "2.0"