# SPDX-FileCopyrightText: 2017 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'LABEL: main'
on: 
  issues:
    types: [opened, edited, milestoned]
  pull_request_target:
    types: [ opened ]
    branches: [ main ]

jobs:

  labeler:
    runs-on: ubuntu-latest

    steps:
    - name: Add Labels
      id: labeler
      uses: jimschubert/labeler-action@e6fb93f2d64d8b0b78d208456f349e9e00698a5d # v2
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
